name: Generate AdGuard Home Whitelist

on:
  push:
    paths:
      - 'whitelist.txt' 
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert domains to AdGuard Home Whitelist syntax
        run: |
          mkdir -p release_output
          OUTPUT_FILE="release_output/allowlist.txt"
          
          NOW=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          cat << EOF > $OUTPUT_FILE
          ! Title: Whitelist for HaGeZi Pro DNS Blocklist
          ! Description: Whitelist rules when using HaGeZi's Pro DNS Blocklist
          ! Homepage: https://github.com/${{ github.repository }}
          ! Last Modified: ${NOW}
          ! Syntax: AdGuard Home Filter Rules
          ! --------------------------------------------------

          EOF

          sed -E '/^[[:space:]]*$/d; /^[[:space:]]*#/d; s/^[[:space:]]*//; s/[[:space:]]*$//' whitelist.txt \
            | sort -u \
            | sed 's/^/@@||/; s/$/^/' >> "$OUTPUT_FILE"

      - name: Deploy allowlist to release branch
        run: |
          if [ -f "release_output/allowlist.txt" ]; then
            cd release_output
            git init
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "build: auto generate adguardhome allowlist"
            git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:release
          else
            echo "No allowlist file found, skip deployment."
          fi