name: Generate AdGuard Home Whitelist

on:
  push:
    paths:
      - 'whitelist.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert domains to AdGuard Home Whitelist syntax
        run: |
          OUTPUT_FILE="allowlist.txt"
          
          NOW=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          cat << EOF > $OUTPUT_FILE
          ! Title: Whitelist for HaGeZi Pro DNS Blocklist
          ! Description: Whitelist rules when using HaGeZi's Pro DNS Blocklist
          ! Homepage: https://github.com/${{ github.repository }}
          ! Last Modified: ${NOW}
          ! Syntax: AdGuard Home Filter Rules
          ! --------------------------------------------------

          EOF

          sed -E '/^[[:space:]]*$/d; /^[[:space:]]*#/d; s/^[[:space:]]*//; s/[[:space:]]*$//' whitelist.txt \
            | sort -u \
            | sed 's/^/@@||/; s/$/^/' >> "$OUTPUT_FILE"

      - name: Deploy allowlist.txt only to release branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: release
          folder: .
          target-folder: .
          clean: false
          single-commit: true